options = trainingOptions("adam", ...
    InitialLearnRate= 0.05 , ...
    LearnRateSchedule="piecewise", ...
    LearnRateDropFactor=0.2, ...
    LearnRateDropPeriod=5, ...
    MaxEpochs=1, ...
    MiniBatchSize=64, ...
    ValidationData= Ds_Val, ...
    ValidationFrequency= 5, ...
    SequenceLength="shortest", ...
    Metrics="rmse",...
    Plots="training-progress");

dlnet = trainnet(Ds_Train, net_1, "mse", options);

ypred = predict(dlnet,XTest);
%% CALCULATE MSE
squaredDifferences = (ypred - TTest).^2;
mse = mean(squaredDifferences)*100  % Percentage
